### PR TITLE
Fix SonarQube Pull Request code insights link

### LINKED ISSUE #1112: SnarQube Pull Request code insights link not pointing to the branch
**Describe the bug**
Currently SonarQube PR code insights link just point to the project but not the branch, it would be needed for this link to the proper link of the scanned code (project and branch)

**To Reproduce**
1. Enable Sonarqube scan
2. Create a Pull request
3. Check code insights sonarqube link
4. See wrong link

**Expected behavior**
SonarQube PR code insights link should point to the proper URL

**Affected version (please complete the following information):**
 - OpenShift: 4.13
 - OpenDevStack 4.4.0

**Additional context**
The code to be modified is [here](https://github.com/opendevstack/ods-jenkins-shared-library/blob/master/src/org/ods/component/ScanWithSonarStage.groovy#L257)

### PR DESCRIPTION
**Pull request by braisvq1996**
closes #1112

### CODE REVIEW

File: src/org/ods/component/ScanWithSonarStage.groovy [hunk 1]
```diff
@@ -253,12 +254,19 @@ class ScanWithSonarStage extends Stage {
...
+        String qualityGateResult, String nexusUrlReport,String sonarProjectKey, String edition, String branch) {
+        String sorQubeScanUrl = ""
         String title = "SonarQube"
         String details = "Please visit the following links to review the SonarQube report:"
         String result = qualityGateResult == "OK" ? "PASS" : "FAIL"
 
+        if (edition != 'community') {
+            sorQubeScanUrl = sonarQube.getSonarQubeHostUrl() + "/dashboard?id=${sonarProjectKey}&branch=${branch}"
+        } else {
+            sorQubeScanUrl = sonarQube.getSonarQubeHostUrl() + "/dashboard?id=${sonarProjectKey}"
```
Comment (jafarre-bi) [inline src/org/ods/component/ScanWithSonarStage.groovy:267]: You can initialize the variable with this value and, if it's not community, then concat the branch.

File: src/org/ods/component/ScanWithSonarStage.groovy [hunk 2]
```diff
@@ -253,12 +254,19 @@ class ScanWithSonarStage extends Stage {
         }
     }
 
-    private createBitbucketCodeInsightReport(String qualityGateResult, String nexusUrlReport, String sonarProjectKey) {
-        String sorQubeScanUrl = sonarQube.getSonarQubeHostUrl() + "/dashboard?id=${sonarProjectKey}"
+    private createBitbucketCodeInsightReport(
+        String qualityGateResult, String nexusUrlReport,String sonarProjectKey, String edition, String branch) {
+        String sorQubeScanUrl = ""
```
Comment (jafarre-bi) [inline src/org/ods/component/ScanWithSonarStage.groovy:259]: See below. you can initialize it here.

**Review by jafarre-bi — CHANGES_REQUESTED** [review]

**Review by jafarre-bi — APPROVED** [review]
