### PR TITLE
Reduce Jira calls

### LINKED ISSUE #654: rm: performance / excessive external calls in LevaDocumentHistory:getReferencedDocumentsVersion
**Describe the bug**
with jenkins transforming all calls into CPS - we need to be extra carefull on large open (functional) loops - that do extensive external work .. leading to NonSerializableExceptions ..

The method in 
https://github.com/opendevstack/ods-jenkins-shared-library/blob/3.x/src/org/ods/orchestration/usecase/LeVADocumentUseCase.groovy#L1729-L1750

is a great (=bad) example ... we go out for each docType, in each document generation, to find the histories against jira (in the most excessive case) - also w/o using any caching

**To Reproduce**
follow up from opendevstack/ods-jenkins-shared-library/#645

**Expected behavior**
performant code :D

**Affected version (please complete the following information):**
 - OpenShift: [3.11/4]
 - OpenDevStack [3.x/master]

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
see below
```

**Additional context**
...

### PR DESCRIPTION
**Pull request by hrcornejo**
Closes #654 and also reduces the number of Jira calls to update the labels of a Test issue. Based in old draft PR #829

### CODE REVIEW

**Review by jorge-romero — APPROVED** [review]

File: src/org/ods/orchestration/util/ConcurrentCache.groovy [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+import com.cloudbees.groovy.cps.NonCPS
+
+import java.util.concurrent.ConcurrentMap
+import java.util.function.Function
+
+class ConcurrentCache<K, V> {
+
+    private final ConcurrentMap<K, V> cache
+
+    ConcurrentCache(def cache) {
```
Comment (jafarre-bi) [inline src/org/ods/orchestration/util/ConcurrentCache.groovy:12]: Let's use a ConcurrentHashMap and don't let the user provide it to avoid possible concurrency issues. We could pass the constructor parameters for the map: initial size, load factor and/or concurrency level for writes.

File: src/org/ods/orchestration/util/ConcurrentCache.groovy [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+    }
+
+    @NonCPS
+    def get(K key,
+            Function<? super K, ? extends V> computeIfAbsent) {
+        cache.computeIfAbsent(key, computeIfAbsent)
+    }
+
+    @NonCPS
+    def put(K key, V value) {
```
Comment (jafarre-bi) [inline src/org/ods/orchestration/util/ConcurrentCache.groovy:23]: For the same reason, to avoid concurrency problems, let's not provider a put method. Elements will be added using the computeIfAbsent only.

**Review by jafarre-bi — CHANGES_REQUESTED** [review]

File: src/org/ods/orchestration/util/ConcurrentCache.groovy (hunk 1 above)
Comment (hrcornejo) [reply src/org/ods/orchestration/util/ConcurrentCache.groovy]: Done

File: src/org/ods/orchestration/util/ConcurrentCache.groovy (hunk 2 above)
Comment (hrcornejo) [reply src/org/ods/orchestration/util/ConcurrentCache.groovy]: Done

**Review by jorge-romero — APPROVED** [review]

**Review by jafarre-bi — APPROVED** [review]
