### PR TITLE
fix for issue 358 in quickstarters:apostrophe in committer name

### LINKED ISSUE #130: Build Openshift Image stage fails if the committer has an apostrophe in their name
I am using the be-springboot quickstarter
Everytime I commit and push code the build fails at the Build Openshift Image stage (see log output below)-my colleague will push the same code-and it will succeed

The issue I believe is that I have an apostrophe character in my last name.

In the patchBuildConfig method of ods-jenkins-shared-library / vars / stageStartOpenshiftBuild.groovy I believe that the ${context.gitCommitAuthor} string needs to be escaped before placed in the odsImageLabels list

===================================
The relevant part of the log is below.

BUILD SUCCESSFUL in 2m 46s
6 actionable tasks: 5 executed, 1 up-to-date
[Pipeline] junit
Recording test results
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Build Openshift Image)
[Pipeline] timeout
Timeout set to expire in 15 min
[Pipeline] {
[Pipeline] writeFile
[Pipeline] sh
[label2019-cd-be-spring-boot-develop] Running shell script
/tmp/workspace/label2019-cd/label2019-cd-be-spring-boot-develop@tmp/durable-29464875/script.sh: line 3: syntax error near unexpected token `('
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // wrap
[Pipeline] echo
Setting BitBucket build status to FAILED ...

### PR DESCRIPTION
**Pull request by EamonnODonnell**
Closes #130 

This is a fix for the issue: see https://github.com/opendevstack/ods-project-quickstarters/issues/358

I decided the easiest solution was to just remove apostrophes from a committers name

### CODE REVIEW

File: vars/stageStartOpenshiftBuild.groovy [hunk 1]
```diff
@@ -27,15 +27,17 @@ def call(def context, def buildArgs = [:], def imageLabels = [:]) {
 }
 
 private void patchBuildConfig(def context, def buildArgs, def imageLabels) {
-  // sanitize commit message
+ // sanitize commit message
   def sanitizedGitCommitMessage = context.gitCommitMessage.replaceAll("[\r\n]+", " ").trim().replaceAll("[\"']+", "")
+  //remove apostrophe in committer name-fix for issue-https://github.com/opendevstack/ods-project-quickstarters/issues/358
```
Comment (henrjk) [inline vars/stageStartOpenshiftBuild.groovy]: I transferred the issue to the shared library. Could you remove the now no longer applicable reference to the issue in the comment?

Comment (EamonnODonnell) [reply vars/stageStartOpenshiftBuild.groovy]: I have removed the link in the comment
